# GNU Make workspace makefile autogenerated by Premake

ifndef config
  config=debug
endif

ifndef verbose
  SILENT = @
endif

ifeq ($(config),debug)
  quigly_asm_config = debug
  quigly_vm_config = debug
endif
ifeq ($(config),release)
  quigly_asm_config = release
  quigly_vm_config = release
endif

PROJECTS := quigly-asm quigly-vm

.PHONY: all clean help $(PROJECTS) 

all: $(PROJECTS)

quigly-asm:
ifneq (,$(quigly_asm_config))
	@echo "==== Building quigly-asm ($(quigly_asm_config)) ===="
	@${MAKE} --no-print-directory -C quigly-asm -f Makefile config=$(quigly_asm_config)
endif

quigly-vm:
ifneq (,$(quigly_vm_config))
	@echo "==== Building quigly-vm ($(quigly_vm_config)) ===="
	@${MAKE} --no-print-directory -C quigly-vm -f Makefile config=$(quigly_vm_config)
endif

clean:
	@${MAKE} --no-print-directory -C quigly-asm -f Makefile clean
	@${MAKE} --no-print-directory -C quigly-vm -f Makefile clean

help:
	@echo "Usage: make [config=name] [target]"
	@echo ""
	@echo "CONFIGURATIONS:"
	@echo "  debug"
	@echo "  release"
	@echo ""
	@echo "TARGETS:"
	@echo "   all (default)"
	@echo "   clean"
	@echo "   quigly-asm"
	@echo "   quigly-vm"
	@echo ""
	@echo "For more information, see https://github.com/premake/premake-core/wiki"